---
name: CI
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Check
        run: |
          ./integrationtest-setup.sh
          go test -v ./...
          ./integrationtest-teardown.sh
      - name: Check mixin
        run: |
          go install github.com/monitoring-mixins/mixtool/cmd/mixtool
          go install github.com/google/go-jsonnet/cmd/jsonnetfmt
          cd couchdb-mixin && make lint build
      - name: Build
        run: go build -v ./...
...
